DROP TABLE IF EXISTS ROOMS;

CREATE TABLE ROOMS
(
    room_number INT UNIQUE NOT NULL,
    bedroom_quantity ENUM('SINGLE', 'DOUBLE', 'TRIPLE') NOT NULL
);

DROP TABLE IF EXISTS RESERVATIONS;

CREATE TABLE RESERVATIONS
(
    id INT generated by default as identity PRIMARY KEY,
    room INT,
    FOREIGN KEY (room) REFERENCES ROOMS(room_number),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    nights_count INT NOT NULL
);